name: Build Pipeline
on: [push, pull_request]

jobs:
  build-linux:
    strategy:
      matrix:
        cxx_std: [c++20]
    runs-on: ubuntu-latest
    env:
      CXX_STD: ${{ matrix.cxx_std }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev xvfb -y
      - name: Build and run tests
        run: xvfb-run ./webview/script/build.sh info # clean format deps check build test

  build-macos:
    strategy:
      matrix:
        cxx_std: [c++20]
    runs-on: macos-latest
    env:
      CXX_STD: ${{ matrix.cxx_std }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build and run tests
        run: ./webview/script/build.sh info clean format deps check build test

  build-windows-msvc:
    strategy:
      matrix:
        cxx_std: [c++20]
        arch: [x64, x86]
    runs-on: windows-latest
    env:
      CXX_STD: ${{ matrix.cxx_std }}
      TARGET_ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build and run tests
        run: ./webview/script/build.bat info clean format deps check build test
        shell: cmd

  build-cs-project:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows-msvc]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - run: dotnet build src/WebView
